import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href="/">Logo</Link>
          <nav>Navigation</nav>
          <Link href="/login">Login</Link>
          <br />
          <Link href="/admin">Admin</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
